### ISSUE TITLE
Toolbar above (Custom CSS - Help)

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#123]
Please what custom css code I can use to put toolbar above (up) ?

**Comment by jingyu9575** [comment]
```css
:root[data-path="panel/panel"] #toolbar {
    order: -1;
}
```
